# Generated by Django 5.1.5 on 2025-02-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='crypto_address',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
